name: Supabase
description: Deploy supabase changes
inputs:
  project_id:
    description: "The project id"
    required: true
    type: string
  access_token:
    description: "Access token for the project"
    required: true
    type: string
  database_url:
    description: "Database url for the project"
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1
      with:
        ruby-version: "3.2"
        bundler-cache: true

    - uses: supabase/setup-cli@ab058987d8d6c725971f6cf9d0b5c98467e30bd1 # v1

    - uses: maierj/fastlane-action@5a3b971aaa26776459bb26894d6c1a1a84a311a7 # v3.1.0
      with:
        lane: "supabase"
      env:
        DATABASE_URL: ${{ inputs.database_url }}
        SUPABASE_ACCESS_TOKEN: ${{ inputs.access_token }}
        SUPABASE_PROJECT_ID: ${{ inputs.project_id }}
