platform :ios, '15.0'

source 'https://cdn.cocoapods.org'

MEDIAPIPE_TASKS_VISION_VERSION = '0.10.21'
MEDIAPIPE_TASKS_GENAI_VERSION = '0.10.24'

target 'iosApp' do
  use_frameworks! :linkage => :static

  pod 'MediaPipeTasksVision', MEDIAPIPE_TASKS_VISION_VERSION
  pod 'MediaPipeTasksGenAI', MEDIAPIPE_TASKS_GENAI_VERSION

  pod 'eyespie', :path => '../eyespie'
end
