name: Development
permissions:
  contents: read
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_call:
    inputs:
      login_email:
        description: The default user to populate login with
        required: false
        type: string
      login_password:
        description: The default password to populate login with
        required: false
        type: string
  workflow_dispatch:

jobs:
  supabase:
    if: false
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: ./.github/actions/supabase
        with:
          access_token: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          project_id: ${{ secrets.SUPABASE_PROJECT_ID }}
          database_url: ${{ secrets.SUPABASE_DB_URL }}

  mobile:
    runs-on: macos-latest
    environment: development

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Forked PR notice
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork }}
        run: |
          echo "Forked PR detected; secrets are not available."

      - name: Create build config
        uses: ./.github/actions/configure-build
        id: build-config
        with:
          android_keystore: ${{ secrets.ANDROID_STORE_FILE }}
          config: ${{ secrets.APP_CONFIG }}
          login_email: ${{ inputs.login_email }}
          login_password: ${{ inputs.login_password }}

      - uses: maierj/fastlane-action@182983d8f94bad9884001c03c1c2786f4c7165ed # v3.2.0
        with:
          lane: "test"
