name: Production
permissions:
  contents: read
on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

jobs:
  supabase:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false

      - uses: ./.github/actions/supabase
        with:
          access_token: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          project_id: ${{ secrets.SUPABASE_PROJECT_ID }}
          database_url: ${{ secrets.SUPABASE_DB_URL }}

  mobile:
    runs-on: macos-latest
    environment: production

    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false

      - name: Create build config
        uses: ./.github/actions/configure-build
        id: build-config
        with:
          android_keystore: ${{ secrets.ANDROID_STORE_FILE }}
          config: ${{ secrets.APP_CONFIG }}
          login_email: ${{ inputs.login_email }}
          login_password: ${{ inputs.login_password }}

      - uses: maierj/fastlane-action@5a3b971aaa26776459bb26894d6c1a1a84a311a7 # v3.1.0
        with:
          lane: "distribute_production"
        env:
          APPLE_CONNECT_ID: "${{ secrets.APPLE_CONNECT_ID }}"
          APPLE_TEAM_ID: "${{ secrets.APPLE_TEAM_ID }}"
          APPLE_USERNAME: "${{ secrets.APPLE_USERNAME }}"
          ANDROID_STORE_FILE: "${{ steps.build-config.outputs.android_keystore }}"
          ANDROID_STORE_PASSWORD: "${{ secrets.ANDROID_STORE_PASSWORD }}"
          ANDROID_KEY_ALIAS: "${{ secrets.ANDROID_KEY_ALIAS }}"
          ANDROID_KEY_PASSWORD: "${{ secrets.ANDROID_KEY_PASSWORD }}"
