name: Production

permissions:
  contents: read

on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:
    inputs:
      login_email:
        description: The default user to populate login with
        required: false
        type: string
      login_password:
        description: The default password to populate login with
        required: false
        type: string

jobs:
  deploy:
    uses: ./.github/workflows/deploy-environment.yml
    with:
      deployment_environment: production
      fastlane_lane: distribute_production
      login_email: ${{ inputs.login_email }}
      login_password: ${{ inputs.login_password }}
