name: Staging

permissions:
  contents: read

on:
  push:
    branches:
      - integration/**
  workflow_call:
    inputs:
      login_email:
        description: The default user to populate login with
        required: false
        type: string
      login_password:
        description: The default password to populate login with
        required: false
        type: string
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy-environment.yml
    with:
      deployment_environment: staging
      fastlane_lane: distribute_staging
      login_email: ${{ inputs.login_email }}
      login_password: ${{ inputs.login_password }}
