name: Build and Test
permissions:
  contents: read
on:
  push:
    branches:
      - feature/**
  pull_request:
    branches:
      - feature/**
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    environment: test

    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Create build config
        uses: ./.github/actions/configure-build
        with:
          config: ${{ secrets.APP_CONFIG }}

      - uses: maierj/fastlane-action@182983d8f94bad9884001c03c1c2786f4c7165ed # v3.2.0
        with:
          lane: "test"
