name: Build and Test
permissions:
  contents: read
on:
  push:
    branches:
      - feature/**
  pull_request:
    branches:
      - feature/**
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    environment: test

    steps:
      - name: Checkout Code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false

      - name: Create build config
        uses: ./.github/actions/configure-build
        with:
          config: ${{ secrets.APP_CONFIG }}

      - uses: maierj/fastlane-action@5a3b971aaa26776459bb26894d6c1a1a84a311a7 # v3.1.0
        with:
          lane: "test"
